### ISSUE TITLE
Some build errors after upgrade Node to v18

### ISSUE THREAD

**Issue by applibs** [zalify/easy-email#317]
JsonToMjml.tsx:20:14 - error TS2339: Property 'children' does not exist on type 'EmailRenderProps'.

JsonToMjml.tsx:33:8 - error TS2322: Type '{ children: ReactNode; dataSource: { [key: string]: any; } | { [key: string]: any; } | undefined; mode: "testing" | "production"; context: IBlockData<any, any> | undefined; }' is not assignable to type 'IntrinsicAttributes & EmailRenderProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & EmailRenderProps'.

TextStyleProps also missing children property.

And many many other components.

**Comment by m-Ryan** [comment]
The latest version has been upgraded to react 18, please check it out. In addition, our default version is node1-6

**Comment by applibs** [comment]
Yeas, I updated and works as expected. Sorry.
